internal/artieclient/destination.go, internal/provider/destination_resource.go
When I change the snowflake username to be incorrect, the ping fails with a helpful error message and the destination doesn't get updated:
When all the settings are correct, the ping succeeds and the update succeeds:
=> Ping destination to test connection before updating

internal/artieclient/destination.go, internal/provider/destination_resource.go, internal/provider/models/translate_destination.go
So we can pass around a destination object that doesn't have a uuid yet. Same pattern that's introduced in https://github.com/artie-labs/terraform-provider-artie/pull/70
=> Add a BaseDestination type 

internal/artieclient/deployment.go, internal/provider/deployment_resource.go, internal/provider/models/translate_deployment.go
Also created a new struct called `BaseDeployment` which doesn't include the fields that are only set by our api (uuid and status) - this allows us to construct an api model for a deployment that hasn't been created yet. Now the client methods that can work on an unsaved deployment take a `BaseDeployment` instead of a full `Deployment`.
Will make the same change for destinations and ssh tunnels after this is merged.
=> Validate before creating a new deployment

internal/artieclient/ssh_tunnel.go, internal/provider/models/translate_ssh_tunnel.go, internal/provider/ssh_tunnel_resource.go
- Added a `BaseSSHTunnel` struct to represent an ssh tunnel that hasn't been saved yet (doesn't have a uuid)
- Made `artieclient.SSHTunnels().Create()` take a `BaseSSHTunnel` instead of a bunch of args
- Turned the translation functions into receiver methods on `SSHTunnelResourceModel` and gave them shorter, clearer names
=> Refactor SSH tunnel model

internal/provider/deployment_resource.go, internal/provider/destination_resource.go, internal/provider/ssh_tunnel_resource.go, internal/provider/tfmodels/deployment.go, internal/provider/tfmodels/destination.go, internal/provider/tfmodels/ssh_tunnel.go
Replaced the `UpdateFromAPIModel()` methods with functions that build up a fully new object instead of taking the existing one and updating all the properties. This removes the need to nil out the other destination configs, and makes the calling code more clear.
=> Construct new state instead of overriding properties on plan data

.gitignore, internal/artieclient/deployment.go
After https://github.com/artie-labs/dashboard/pull/3243, the endpoint for updating a deployment no longer takes this flag.
=> Don't need this flag anymore when updating a deployment

internal/provider/deployment_resource.go, internal/provider/destination_resource.go, internal/provider/ssh_tunnel_resource.go
Just realized that if an error happens in a helper function, it wasn't getting reported because we were passing the diagnostics to those functions without pointers so they didn't get directly mutated.
=> Pass diagnostics to helper functions as pointers so changes are preserved

internal/artieclient/client.go
Some of our api endpoints now return 204 (no content) if they succeed and no response content is needed (e.g. validating and deleting objects). The provider was only accepting explicit 200s as success responses; instead it should accept anything in the 1xx or 2xx range.
=> Handle 204 no content responses

internal/provider/tfmodels/deployment_table.go, internal/provider/tfmodels/util.go
- Checking if a uuid is null/empty before trying to parse it
- One more place that was using `MustParse` instead of surfacing diagnostics
=> `parseUUID` improvements

internal/artieclient/deployment.go
We were only doing this to the response from the Get & Update endpoints; need to do it for Create too, or else you get an inconsistent state error if you create a deployment with some advanced settings specified.
=> Unnest advanced settings after creating a deployment

docs/resources/destination.md, internal/provider/destination_resource.go
- Secret access key should be required, not optional
- Need to skip trying to test the connection before creating a new S3 destination
=> Fixes for S3

docs/resources/deployment.md, internal/artieclient/deployment.go, internal/provider/deployment_resource.go, internal/provider/tfmodels/deployment.go
This allows customers to specify which data plane to deploy this into.
=> Supporting `data_plane_name` for deployment

internal/provider/deployment_resource.go
The new fields for `snapshot_host` and `data_plane_name` should be optional in the config and use whatever existing value the dashboard api returns if they aren't specified. To achieve this, the field needs the following settings:
- Optional: true
- Computed: true
- Plan modifiers: use state for unknown
- No default value
=> Fix optional fields (use computed + planmodifier + no default)

go.mod, internal/provider/tfmodels/deployment.go, internal/provider/tfmodels/deployment_test.go
Using `types.Object` instead of our custom type so that it supports unknown values.
I also added tests around this
=> Flush Config to use `types.Object`

internal/provider/tfmodels/source_reader.go
- Check that the tf map isn't null or unknown before trying to convert it to api model
- Move map building into `SourceReaderTablesFromAPIModel`
=> Source reader table improvements

go.mod, internal/artieclient/client.go, internal/provider/pipeline_resource.go, internal/provider/provider.go
This way, we can control the parallelism for mutating pipeline resources and not run into timeouts that arise from trying to acquire a git lock
=> Adding a semaphore around pipeline

.github/workflows/test.yml, internal/artieclient/source_reader.go, internal/provider/source_reader_resource.go, internal/provider/source_reader_resource_test.go
Same idea as https://github.com/artie-labs/terraform-provider-artie/pull/174
Also added more validation for the tables config on source readers.
=> Validate & deploy shared source readers after creating/updating

internal/provider/tfmodels/connector.go, internal/provider/tfmodels/deployment_source.go
This is the only source config type that's used by both the Connector resource and the deprecated Deployment resource - moving it into the connector file in preparation for removing the other one.
=> Move dynamo config type out of deprecated file

internal/artieclient/pipeline.go
This setting was moved to the source reader settings so it should have been deleted from this struct. It's already fully unused.
=> Remove unused field

docs/resources/connector.md, docs/resources/source_reader.md, docs/resources/ssh_tunnel.md, examples/resources/artie_connector/import.sh, examples/resources/artie_source_reader/import.sh, examples/resources/artie_ssh_tunnel/import.sh
Now that we have the "View UUIDs" button, it's easy to see the other related objects to a pipeline.
=> Add import instructions to the rest of the resources

internal/artieclient/pipeline.go
Our endpoint now accepts this and validates it if passed in.
=> Include advanced settings when validating destination

internal/artieclient/client.go
This PR logs out the response body if there's an error. When we return a 404 error, sometimes there's additional context such as the connector or specified source reader is not found.
It'd be nice to display that so that our customers can more effectively troubleshoot issues on their own
=> Update Artie Client to return body
